name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  industrial_ci:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: 'ros-industrial/industrial_ci@master'
        env:
          CI_NAME: focal
          OS_NAME: ubuntu
          OS_CODE_NAME: focal
          ROS_DISTRO: foxy
          ROS_REPO: main
          DOCKER_IMAGE: ros:foxy
